<h1>А-02-21 Енгоян Сергей ЛР 2</h1>

In [112]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer 
import numpy as np

In [113]:
categories = ['comp.windows.x', 'rec.sport.baseball', 'rec.sport.hockey']
remove = ('headers', 'footers', 'quotes')

twenty_train = fetch_20newsgroups(subset='train', shuffle=True, random_state=28, categories=categories, remove=remove)
twenty_test = fetch_20newsgroups(subset='test', shuffle=True, random_state=28, categories=categories, remove=remove)

Выведем по одному тексту каждой их 3 категорий

In [114]:
print(twenty_train.target_names[twenty_train.target[5]], twenty_train.data[5])

comp.windows.x 
I think the original post was searching for existing implementations of
f.i. Gouroud-shading of triangles. This is fairly complex to do with plain
X. Simpler shading models are implemented already, f.i. in x3d (ask archie
where to get the latest version).
For Gouroud, a fast implementation will be possible utilizing some extension
only, either MIT-SHM to do the shade in an image and fast update the window
with it, or PEX/OpenGL which should be able to shade themselves. The portable
'vanilla X' way would be to shade in a normal XImage and use XPutImage(),
what would be good enough to do static things as f.i. fractal landscapes
or such stuff.

To speak about POVRay, the X previewer that comes with the original source
package is not that good, especially in speed, protocol-friendlyness and
ICCCM compliance. Have a look on x256q, my own preview code. It is on

141.76.1.11:pub/gfx/ray/misc/x256q/

The README states the points where it is better than xwindow.c from
POVRay 1.0

In [115]:
print(twenty_train.target_names[twenty_train.target[1]], twenty_train.data[1])

rec.sport.hockey 


Well, it seems that the Habs have been much talked-about of late, so here's my
$0.02.  These guys have absolutely no concept of how to play in front of the
damn net!!!  Watch them in the offensive zone, especially on the powerplay. 
Damphousse or Lebeau will skate all over the bloody zone, maybe pass to the
point, get it back, skate some more, pass it around....BUT WHERE'S THE SHOT??!
Answer: the shot is totally useless because they lack a forward who stands
in front of the net a la` Neely, Shanahan, Tocchet, etc etc.  Too bad 
Demers won't put Dipietro or LeClair on the powerplay more often.  Dammit,
even Ewen would at least cause some disruptions.  Montreal desperately needs
a power forward with some talent, IMO.

Then watch them in their own zone. Patrick Roy is screened on everything. Say
what you want about his performance; IMNSHO he cannot stop what he cannot see. 
And Montreal's defence does a miserable job of clearing the front of the net. 
Last night agains

In [116]:
print(twenty_train.target_names[twenty_train.target[13]], twenty_train.data[13])

rec.sport.baseball Amazingly, pitchers, no matter how good their mechanics, are
not machines.  Cy Young winners don't pitch in a vaccuum, unaware
of how their offenses are doing.

	The Braves' pitching staff is already showing signs of
cracking under the strain of knowing they're not going to get many
(if any) runs.  Unfortunately, the Braves' pitchers were so bad for so
long that the organization put so much stress (and I mean *stress*)
on pitching that they completely ignored hitting.

	The Braves right now are looking woefully similar to the Braves of
the mid-seventies.  Heaven help us.
 


<h>Стемминг</h>

In [117]:
from nltk.stem import *
from nltk import word_tokenize
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\User\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [118]:
porter_stemmer = PorterStemmer()
stem_train = []
stem_test = []
for text in twenty_train.data:
    nltk_tokens = word_tokenize(text)
    line = ''
    for word in nltk_tokens:
        line += ' ' + porter_stemmer.stem(word)
    stem_train.append(line)

for text in twenty_test.data:
    nltk_tokens = word_tokenize(text)
    line = ''
    for word in nltk_tokens:
        line += ' ' + porter_stemmer.stem(word)
    stem_test.append(line)

In [119]:
print(twenty_train.data[0])
print(stem_train[0])

Ok, it seems that everyone else in canada was treated to the 
REAL ABC telecast while only the people on ROGERS TV in Surrey BC 
were treated to two channels with Don "I stink as a Commentator" Whitman
doing the play-by-play.
 ok , it seem that everyon els in canada wa treat to the real abc telecast while onli the peopl on roger tv in surrey bc were treat to two channel with don `` i stink as a comment '' whitman do the play-by-play .


<h>Векторизация</h>

In [120]:
vect_1 = CountVectorizer(max_features=10000)

train_data = vect_1.fit_transform(twenty_train.data)
test_data = vect_1.transform(twenty_test.data)

In [121]:
x_1 = list(zip(vect_1.get_feature_names_out(), np.ravel(train_data.sum(axis=0))))
def SortbyTF(inputStr):
    return inputStr[1]
x_1.sort(key=SortbyTF, reverse = True)

for _ in x_1[:20]:
    print(_)

('the', np.int64(15749))
('to', np.int64(7012))
('and', np.int64(5437))
('of', np.int64(5008))
('in', np.int64(4583))
('is', np.int64(3967))
('that', np.int64(3001))
('for', np.int64(2833))
('it', np.int64(2597))
('on', np.int64(2307))
('you', np.int64(2059))
('this', np.int64(2006))
('be', np.int64(1979))
('with', np.int64(1708))
('have', np.int64(1652))
('are', np.int64(1634))
('he', np.int64(1524))
('if', np.int64(1522))
('as', np.int64(1453))
('but', np.int64(1438))


In [122]:
category_names = twenty_train.target_names
category_indices = twenty_train.target

word_freq_pairs_1 = {}
word_list_1 = {0:[], 1:[], 2:[]}


for cat_idx, cat_name in enumerate(twenty_train.target_names):
    print(f"\nЧастые термины для категории: {cat_name}")

    cat_mask = (category_indices == cat_idx)
    cat_data = train_data[cat_mask]
    
    word_frequencies = np.ravel(cat_data.sum(axis=0))
    word_freq_pairs_1[cat_idx] = list(zip(vect_1.get_feature_names_out(), word_frequencies))
    word_freq_pairs_1[cat_idx].sort(key=SortbyTF, reverse=True)

    for word, freq in word_freq_pairs_1[cat_idx]:
        if freq != 0:
            word_list_1[cat_idx].append(word)

    for word, freq in word_freq_pairs_1[cat_idx][:20]:
        print(f"{word}: {freq}")
    


Частые термины для категории: comp.windows.x
the: 6750
to: 3486
and: 2447
of: 2296
is: 2269
in: 1848
for: 1394
it: 1261
on: 1141
that: 1130
this: 1125
you: 1066
be: 956
are: 893
if: 836
with: 821
or: 778
can: 756
an: 730
not: 699

Частые термины для категории: rec.sport.baseball
the: 3508
to: 1481
and: 1312
of: 1142
in: 1114
that: 882
is: 842
he: 738
for: 580
it: 543
have: 494
was: 466
but: 451
be: 448
you: 443
on: 441
this: 416
they: 409
at: 404
with: 393

Частые термины для категории: rec.sport.hockey
the: 5491
to: 2045
and: 1678
in: 1621
of: 1570
that: 989
for: 859
is: 856
it: 793
he: 776
was: 731
on: 725
be: 575
you: 550
at: 547
but: 532
have: 512
with: 494
team: 478
as: 466


Отсечение стоп-слов

In [123]:
vect_2 = CountVectorizer(max_features=10000, stop_words='english')

train_data = vect_2.fit_transform(twenty_train.data)
test_data = vect_2.transform(twenty_test.data)

x_2 = list(zip(vect_2.get_feature_names_out(), np.ravel(train_data.sum(axis=0))))
def SortbyTF(inputStr):
    return inputStr[1]
x_2.sort(key=SortbyTF, reverse = True)

for _ in x_2[:20]:
    print(_)

category_names = twenty_train.target_names
category_indices = twenty_train.target

word_freq_pairs_2 = {}
word_list_2 = {0:[], 1:[], 2:[]}


for cat_idx, cat_name in enumerate(twenty_train.target_names):
    print(f"\nЧастые термины для категории: {cat_name}")

    cat_mask = (category_indices == cat_idx)
    cat_data = train_data[cat_mask]
    
    word_frequencies = np.ravel(cat_data.sum(axis=0))
    word_freq_pairs_2[cat_idx] = list(zip(vect_2.get_feature_names_out(), word_frequencies))
    word_freq_pairs_2[cat_idx].sort(key=SortbyTF, reverse=True)

    for word, freq in word_freq_pairs_2[cat_idx]:
        if freq != 0:
            word_list_2[cat_idx].append(word)

    for word, freq in word_freq_pairs_2[cat_idx][:20]:
        print(f"{word}: {freq}")

('team', np.int64(679))
('game', np.int64(633))
('year', np.int64(629))
('file', np.int64(586))
('like', np.int64(582))
('10', np.int64(580))
('window', np.int64(573))
('edu', np.int64(544))
('use', np.int64(512))
('don', np.int64(502))
('just', np.int64(480))
('time', np.int64(466))
('new', np.int64(437))
('good', np.int64(434))
('think', np.int64(429))
('play', np.int64(427))
('season', np.int64(424))
('program', np.int64(417))
('games', np.int64(416))
('11', np.int64(415))

Частые термины для категории: comp.windows.x
file: 579
window: 571
use: 459
program: 412
server: 385
edu: 377
motif: 356
widget: 354
entry: 351
output: 315
available: 306
com: 274
set: 274
using: 269
mit: 254
application: 253
like: 247
information: 245
sun: 240
does: 232

Частые термины для категории: rec.sport.baseball
year: 310
game: 204
good: 200
team: 195
think: 189
don: 186
00: 175
just: 161
like: 153
games: 149
better: 140
baseball: 137
hit: 137
runs: 137
players: 135
time: 131
02: 125
won: 124
league: 118


Пункт А для выборки со стеммингом

In [124]:
vect_3 = CountVectorizer(max_features=10000)

train_data = vect_3.fit_transform(stem_train)
test_data = vect_3.transform(stem_test)

x_3 = list(zip(vect_3.get_feature_names_out(), np.ravel(train_data.sum(axis=0))))
def SortbyTF(inputStr):
    return inputStr[1]
x_3.sort(key=SortbyTF, reverse = True)

for _ in x_3[:20]:
    print(_)

category_names = twenty_train.target_names
category_indices = twenty_train.target

word_freq_pairs_3 = {}
word_list_3 = {0:[], 1:[], 2:[]}

for cat_idx, cat_name in enumerate(twenty_train.target_names):
    print(f"\nЧастые термины для категории: {cat_name}")

    cat_mask = (category_indices == cat_idx)
    cat_data = train_data[cat_mask]
    
    word_frequencies = np.ravel(cat_data.sum(axis=0))
    word_freq_pairs_3[cat_idx] = list(zip(vect_3.get_feature_names_out(), word_frequencies))
    word_freq_pairs_3[cat_idx].sort(key=SortbyTF, reverse=True)
    
    for word, freq in word_freq_pairs_3[cat_idx]:
        if freq != 0:
            word_list_3[cat_idx].append(word)

    for word, freq in word_freq_pairs_3[cat_idx][:20]:
        print(f"{word}: {freq}")
        

('the', np.int64(15747))
('to', np.int64(7012))
('and', np.int64(5437))
('of', np.int64(5008))
('in', np.int64(4586))
('is', np.int64(4065))
('that', np.int64(3003))
('for', np.int64(2833))
('it', np.int64(2787))
('on', np.int64(2310))
('be', np.int64(2168))
('you', np.int64(2059))
('thi', np.int64(2006))
('have', np.int64(1795))
('with', np.int64(1708))
('are', np.int64(1677))
('he', np.int64(1524))
('if', np.int64(1522))
('not', np.int64(1467))
('wa', np.int64(1456))

Частые термины для категории: comp.windows.x
the: 6749
to: 3486
and: 2447
is: 2302
of: 2296
in: 1849
for: 1394
it: 1384
on: 1143
that: 1131
thi: 1125
you: 1066
be: 1015
use: 988
are: 904
if: 836
with: 821
or: 778
file: 763
not: 760

Частые термины для категории: rec.sport.baseball
the: 3507
to: 1481
and: 1312
of: 1142
in: 1116
that: 883
is: 876
he: 738
for: 580
it: 561
have: 529
be: 510
wa: 493
but: 451
you: 443
on: 442
thi: 416
they: 409
year: 405
at: 404

Частые термины для категории: rec.sport.hockey
the: 5491
to: 20

In [125]:
def jaccard_similarity(list1, list2):
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(set(list1)) + len(set(list2))) - intersection
    return float(intersection) / union

In [126]:
print(f"Жаккар между {twenty_train.target_names[0]} и {twenty_train.target_names[1]}:", jaccard_similarity(word_list_1[0], word_list_1[1]))
print(f"Жаккар между {twenty_train.target_names[0]} и {twenty_train.target_names[2]}:", jaccard_similarity(word_list_1[0], word_list_1[2]))
print(f"Жаккар между {twenty_train.target_names[1]} и {twenty_train.target_names[2]}:", jaccard_similarity(word_list_1[1], word_list_1[2]))
print('Отсечение стоп-слов')
print(f"Жаккар между {twenty_train.target_names[0]} и {twenty_train.target_names[1]}:", jaccard_similarity(word_list_2[0], word_list_2[1]))
print(f"Жаккар между {twenty_train.target_names[0]} и {twenty_train.target_names[2]}:", jaccard_similarity(word_list_2[0], word_list_2[2]))
print(f"Жаккар между {twenty_train.target_names[1]} и {twenty_train.target_names[2]}:", jaccard_similarity(word_list_2[1], word_list_2[2]))
print('Стемминг и стоп-слова')
print(f"Жаккар между {twenty_train.target_names[0]} и {twenty_train.target_names[1]}:", jaccard_similarity(word_list_3[0], word_list_3[1]))
print(f"Жаккар между {twenty_train.target_names[0]} и {twenty_train.target_names[2]}:", jaccard_similarity(word_list_3[0], word_list_3[2]))
print(f"Жаккар между {twenty_train.target_names[1]} и {twenty_train.target_names[2]}:", jaccard_similarity(word_list_3[1], word_list_3[2]))




Жаккар между comp.windows.x и rec.sport.baseball: 0.3481897478790775
Жаккар между comp.windows.x и rec.sport.hockey: 0.3608225108225108
Жаккар между rec.sport.baseball и rec.sport.hockey: 0.4852550478214665
Отсечение стоп-слов
Жаккар между comp.windows.x и rec.sport.baseball: 0.3201590553078684
Жаккар между comp.windows.x и rec.sport.hockey: 0.3326839826839827
Жаккар между rec.sport.baseball и rec.sport.hockey: 0.46455834242093785
Стемминг и стоп-слова
Жаккар между comp.windows.x и rec.sport.baseball: 0.32325903538597156
Жаккар между comp.windows.x и rec.sport.hockey: 0.3147885014755711
Жаккар между rec.sport.baseball и rec.sport.hockey: 0.44285714285714284


Наивный Байес

In [127]:
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.preprocessing import FunctionTransformer

In [128]:
def fit_model(text_clf, y_train, y_test):
    text_clf = text_clf.fit(y_train, twenty_train.target)
    prediction = text_clf.predict(y_test)

    y_test = twenty_test.target
    print ('Prediction and test: ')
    print (prediction)
    print (y_test)
    print ('Confusion matrix: ')
    print (confusion_matrix(y_test, prediction))
    print ('Accuracy score: ', accuracy_score(prediction, y_test))
    print(classification_report(y_test, prediction))

In [129]:
to_dense = FunctionTransformer(lambda x: x.toarray(), accept_sparse=True)


text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000)),
                ('to_dense', to_dense),
                ('clf', GaussianNB()),
            ])   

fit_model(text_clf, twenty_train.data, twenty_test.data)

Prediction and test: 
[0 2 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[363  18  14]
 [  9 350  38]
 [  3  37 359]]
Accuracy score:  0.9000839630562553
              precision    recall  f1-score   support

           0       0.97      0.92      0.94       395
           1       0.86      0.88      0.87       397
           2       0.87      0.90      0.89       399

    accuracy                           0.90      1191
   macro avg       0.90      0.90      0.90      1191
weighted avg       0.90      0.90      0.90      1191



In [130]:
fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[357  26  12]
 [  7 352  38]
 [  1  45 353]]
Accuracy score:  0.8916876574307305
              precision    recall  f1-score   support

           0       0.98      0.90      0.94       395
           1       0.83      0.89      0.86       397
           2       0.88      0.88      0.88       399

    accuracy                           0.89      1191
   macro avg       0.90      0.89      0.89      1191
weighted avg       0.90      0.89      0.89      1191



In [131]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000, stop_words='english')),
                ('to_dense', to_dense),
                ('clf', GaussianNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[359  26  10]
 [  7 352  38]
 [  4  46 349]]
Accuracy score:  0.8900083963056256
              precision    recall  f1-score   support

           0       0.97      0.91      0.94       395
           1       0.83      0.89      0.86       397
           2       0.88      0.87      0.88       399

    accuracy                           0.89      1191
   macro avg       0.89      0.89      0.89      1191
weighted avg       0.89      0.89      0.89      1191



In [132]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000, stop_words='english')),
                ('tfidf', TfidfTransformer(use_idf = False)),
                ('to_dense', to_dense),
                ('clf', GaussianNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[364  22   9]
 [  8 350  39]
 [  4  37 358]]
Accuracy score:  0.9000839630562553
              precision    recall  f1-score   support

           0       0.97      0.92      0.94       395
           1       0.86      0.88      0.87       397
           2       0.88      0.90      0.89       399

    accuracy                           0.90      1191
   macro avg       0.90      0.90      0.90      1191
weighted avg       0.90      0.90      0.90      1191



In [133]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000, stop_words='english')),
                ('tfidf', TfidfTransformer(use_idf = True)),
                ('to_dense', to_dense),
                ('clf', GaussianNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[364  20  11]
 [ 11 333  53]
 [  4  41 354]]
Accuracy score:  0.8824517212426533
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       395
           1       0.85      0.84      0.84       397
           2       0.85      0.89      0.87       399

    accuracy                           0.88      1191
   macro avg       0.88      0.88      0.88      1191
weighted avg       0.88      0.88      0.88      1191



In [134]:
feat = [100, 1000, 5000, 10000]
for f in feat:
    print(f'max features: {f}')
    text_clf = Pipeline([
                    ('vect', CountVectorizer(max_features= f, stop_words='english')),
                    ('tfidf', TfidfTransformer(use_idf = False)),
                    ('to_dense', to_dense),
                    ('clf', GaussianNB()),
                ])   

    fit_model(text_clf, stem_train, stem_test)

max features: 100


Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[363  28   4]
 [ 61 303  33]
 [ 42 166 191]]
Accuracy score:  0.7195633921074727
              precision    recall  f1-score   support

           0       0.78      0.92      0.84       395
           1       0.61      0.76      0.68       397
           2       0.84      0.48      0.61       399

    accuracy                           0.72      1191
   macro avg       0.74      0.72      0.71      1191
weighted avg       0.74      0.72      0.71      1191

max features: 1000
Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[359  31   5]
 [  6 364  27]
 [  2  79 318]]
Accuracy score:  0.8740554156171285
              precision    recall  f1-score   support

           0       0.98      0.91      0.94       395
           1       0.77      0.92      0.84       397
           2       0.91      0.80      0.85       399

    accuracy                           0.87      1191
   macro a

In [135]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 5000, stop_words='english')),
                ('tfidf', TfidfTransformer(use_idf = False)),
                ('to_dense', to_dense),
                ('clf', GaussianNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

vect_4 = CountVectorizer(stop_words='english')

train_data = vect_4.fit_transform(stem_train)
test_data = vect_4.transform(stem_test)
print(f'Длина словаря: {len(vect_4.get_feature_names_out())}')

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[369  20   6]
 [  6 353  38]
 [  3  34 362]]
Accuracy score:  0.910159529806885
              precision    recall  f1-score   support

           0       0.98      0.93      0.95       395
           1       0.87      0.89      0.88       397
           2       0.89      0.91      0.90       399

    accuracy                           0.91      1191
   macro avg       0.91      0.91      0.91      1191
weighted avg       0.91      0.91      0.91      1191

Длина словаря: 17254


Итоговый вариант:
- стемминг
- отсекая стоп-слова
- TF
- max_features: 5000

In [136]:
text_clf = Pipeline([
                ('vect', CountVectorizer(stop_words='english')),
                ('tfidf', TfidfTransformer(use_idf = False)),
                ('to_dense', to_dense),
                ('clf', GaussianNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[364  21  10]
 [ 11 351  35]
 [  4  40 355]]
Accuracy score:  0.8984047019311503
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       395
           1       0.85      0.88      0.87       397
           2       0.89      0.89      0.89       399

    accuracy                           0.90      1191
   macro avg       0.90      0.90      0.90      1191
weighted avg       0.90      0.90      0.90      1191



Мультиноминальный Наивный Байес

In [137]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000)),
                ('to_dense', to_dense),
                ('clf', MultinomialNB()),
            ])   

fit_model(text_clf, twenty_train.data, twenty_test.data)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[376  10   9]
 [ 12 364  21]
 [  5  74 320]]
Accuracy score:  0.8900083963056256
              precision    recall  f1-score   support

           0       0.96      0.95      0.95       395
           1       0.81      0.92      0.86       397
           2       0.91      0.80      0.85       399

    accuracy                           0.89      1191
   macro avg       0.89      0.89      0.89      1191
weighted avg       0.89      0.89      0.89      1191



In [138]:
fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[378  10   7]
 [ 12 362  23]
 [  4  76 319]]
Accuracy score:  0.889168765743073
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       395
           1       0.81      0.91      0.86       397
           2       0.91      0.80      0.85       399

    accuracy                           0.89      1191
   macro avg       0.89      0.89      0.89      1191
weighted avg       0.89      0.89      0.89      1191



In [139]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000, stop_words='english')),
                ('to_dense', to_dense),
                ('clf', MultinomialNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[380   8   7]
 [ 13 358  26]
 [  2  46 351]]
Accuracy score:  0.9143576826196473
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       395
           1       0.87      0.90      0.89       397
           2       0.91      0.88      0.90       399

    accuracy                           0.91      1191
   macro avg       0.92      0.91      0.91      1191
weighted avg       0.91      0.91      0.91      1191



In [140]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000, stop_words='english')),
                ('tfidf', TfidfTransformer(use_idf = False)),
                ('to_dense', to_dense),
                ('clf', MultinomialNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[379   4  12]
 [ 15 332  50]
 [  3  15 381]]
Accuracy score:  0.9168765743073047
              precision    recall  f1-score   support

           0       0.95      0.96      0.96       395
           1       0.95      0.84      0.89       397
           2       0.86      0.95      0.90       399

    accuracy                           0.92      1191
   macro avg       0.92      0.92      0.92      1191
weighted avg       0.92      0.92      0.92      1191



In [141]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000, stop_words='english')),
                ('tfidf', TfidfTransformer(use_idf = True)),
                ('to_dense', to_dense),
                ('clf', MultinomialNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[379   5  11]
 [ 12 343  42]
 [  4  12 383]]
Accuracy score:  0.927791771620487
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       395
           1       0.95      0.86      0.91       397
           2       0.88      0.96      0.92       399

    accuracy                           0.93      1191
   macro avg       0.93      0.93      0.93      1191
weighted avg       0.93      0.93      0.93      1191



In [142]:
feat = [100, 1000, 5000, 10000]
for f in feat:
    print(f'max features: {f}')
    text_clf = Pipeline([
                    ('vect', CountVectorizer(max_features= f, stop_words='english')),
                    ('tfidf', TfidfTransformer(use_idf = True)),
                    ('to_dense', to_dense),
                    ('clf', MultinomialNB()),
                ])   

    fit_model(text_clf, stem_train, stem_test)

max features: 100
Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[351  22  22]
 [ 29 270  98]
 [ 16 109 274]]
Accuracy score:  0.7514693534844669
              precision    recall  f1-score   support

           0       0.89      0.89      0.89       395
           1       0.67      0.68      0.68       397
           2       0.70      0.69      0.69       399

    accuracy                           0.75      1191
   macro avg       0.75      0.75      0.75      1191
weighted avg       0.75      0.75      0.75      1191

max features: 1000
Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[373  13   9]
 [ 14 331  52]
 [  2  44 353]]
Accuracy score:  0.887489504617968
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       395
           1       0.85      0.83      0.84       397
           2       0.85      0.88      0.87       399

    accuracy                           0.89    

In [143]:
text_clf = Pipeline([
                ('vect', CountVectorizer(stop_words='english')),
                ('tfidf', TfidfTransformer(use_idf = True)),
                ('to_dense', to_dense),
                ('clf', MultinomialNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

vect_5 = CountVectorizer(stop_words='english')

train_data = vect_5.fit_transform(stem_train)
test_data = vect_5.transform(stem_test)
print(f'Длина словаря: {len(vect_5.get_feature_names_out())}')

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[379   5  11]
 [ 12 337  48]
 [  3   9 387]]
Accuracy score:  0.926112510495382
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       395
           1       0.96      0.85      0.90       397
           2       0.87      0.97      0.92       399

    accuracy                           0.93      1191
   macro avg       0.93      0.93      0.93      1191
weighted avg       0.93      0.93      0.93      1191

Длина словаря: 17254


Итоговый вариант:
- стемминг
- отсекая стоп-слова
- TF-IDF
- max_features: 10000

In [144]:
text_clf = Pipeline([
                ('vect', CountVectorizer(max_features= 10000, stop_words='english')),
                ('tfidf', TfidfTransformer(use_idf = True)),
                ('to_dense', to_dense),
                ('clf', MultinomialNB()),
            ])   

fit_model(text_clf, stem_train, stem_test)

Prediction and test: 
[0 1 1 ... 1 0 2]
[0 1 1 ... 1 0 2]
Confusion matrix: 
[[379   5  11]
 [ 12 343  42]
 [  4  12 383]]
Accuracy score:  0.927791771620487
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       395
           1       0.95      0.86      0.91       397
           2       0.88      0.96      0.92       399

    accuracy                           0.93      1191
   macro avg       0.93      0.93      0.93      1191
weighted avg       0.93      0.93      0.93      1191



Влияние этапов:
- Стемминг - должен объединить схожие термины не сильно уменьшая информативность словаря. Уменьшает кол-во уникальных слов -> умменьшение словаря, повышает эффективность обработки. Но также могут появляться ошибки при обработки слов с одинаковым стеммом, но разным смыслом.
- Отсечение стоп-слов - исключить самые часто встречающиеся термины (союзы, предлоги, частицы и т.п.) и слишком редко встречающиеся слова. Уменьшение размера словаря, анализ более значимых слов в тексте. Появление смысловых ошибок.
- Взешивание:
    - Логическое - простая модель анализирующая все слова встречающиеся в тексте. Но часто встречающиеся слова могут доминировать даже если они не важны. Не учитывается длина текста. Не учитываются схожие слова.
    - TF - учитывает частоту вхождения слова в текст. Учитывается длина текста. 
    - IDF - уменьшает вес широкоупотребляемых слов в различных документах и повышает значимость тематических слов в конкретном тексте.
- Максимальное кол-во терминов:
    - Малое кол-во терминов упрощает модель, снижает переобучение. Теряются редкие тематические термины, плохое различие классов. 
    - Большое кол0во терминов учитывает больше уникальных слов, что помогает избежать потери информации. Лучше подходит для сложынх тематических текстов. Но усложняет модель, возможно переобучение, появляется шум.