<h1>А-02-21 Енгоян Сергей ЛР 3</h1>

In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer 
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

In [2]:
categories = ['comp.windows.x', 'rec.sport.baseball', 'rec.sport.hockey']
remove = ('headers', 'footers', 'quotes')

twenty_train = fetch_20newsgroups(subset='train', shuffle=True, random_state=28, categories=categories, remove=remove)
twenty_test = fetch_20newsgroups(subset='test', shuffle=True, random_state=28, categories=categories, remove=remove)

In [34]:
text_clf_RF = Pipeline([('vect', CountVectorizer()),
                    ('tfidf', TfidfTransformer()),
                    ('clf', RandomForestClassifier ()),]) 

text_clf_MNB = Pipeline([('vect', CountVectorizer()),
                    ('tfidf', TfidfTransformer()),
                    ('clf', MultinomialNB()),])

RF_parameters = {'vect__max_features': (100,1000,5000,10000),
              'vect__stop_words': ('english', None),
              'tfidf__use_idf': (True, False),              
              'clf__n_estimators': (5, 30, 100),
              'clf__criterion': ('gini', 'entropy'),
              'clf__max_depth': (5, 15, 50),
              }

MNB_parameters = {'vect__max_features': (100,1000,5000,10000),
              'vect__stop_words': ('english', None),
              'tfidf__use_idf': (True, False),
              'clf__alpha': (0.1, 1.2),
              }

gs_RF = GridSearchCV(text_clf_RF, RF_parameters, n_jobs=-1, cv=3, scoring = 'f1_weighted')
gs_MNB = GridSearchCV(text_clf_MNB, MNB_parameters, n_jobs=-1, cv=3, scoring = 'f1_weighted')

gs_RF = gs_RF.fit(twenty_train.data, twenty_train.target)
gs_MNG = gs_MNB.fit(twenty_train.data, twenty_train.target)

In [36]:
from sklearn.metrics import confusion_matrix, classification_report

print("Random Forest:")
prediction_RF = gs_RF.predict(twenty_test.data)
print(gs_RF.best_params_)
print(gs_RF.best_score_)
print (confusion_matrix(twenty_test.target, prediction_RF))
print(classification_report(twenty_test.target, prediction_RF))

print("Multinomial NB:")
prediction_MNB = gs_MNB.predict(twenty_test.data)
print(gs_MNB.best_params_)
print(gs_MNB.best_score_)
print (confusion_matrix(twenty_test.target, prediction_MNB))
print(classification_report(twenty_test.target, prediction_MNB))



Random Forest:
{'clf__criterion': 'entropy', 'clf__max_depth': 15, 'clf__n_estimators': 100, 'tfidf__use_idf': True, 'vect__max_features': 10000, 'vect__stop_words': 'english'}
0.87045708114994
[[338  56   1]
 [ 19 363  15]
 [  3  87 309]]
              precision    recall  f1-score   support

           0       0.94      0.86      0.90       395
           1       0.72      0.91      0.80       397
           2       0.95      0.77      0.85       399

    accuracy                           0.85      1191
   macro avg       0.87      0.85      0.85      1191
weighted avg       0.87      0.85      0.85      1191

Multinomial NB:
{'clf__alpha': 0.1, 'tfidf__use_idf': True, 'vect__max_features': 10000, 'vect__stop_words': 'english'}
0.9321950837845826
[[376   9  10]
 [  9 353  35]
 [  4  15 380]]
              precision    recall  f1-score   support

           0       0.97      0.95      0.96       395
           1       0.94      0.89      0.91       397
           2       0.89      0.

<h>Векторизуем обучающую выборку</h>

In [1]:
import gensim.downloader

glove_model = gensim.downloader.load("glove-wiki-gigaword-100")
print(glove_model['cat'])
glove_model.most_similar("cat")


[==================================================] 100.0% 128.1/128.1MB downloaded
[ 0.23088    0.28283    0.6318    -0.59411   -0.58599    0.63255
  0.24402   -0.14108    0.060815  -0.7898    -0.29102    0.14287
  0.72274    0.20428    0.1407     0.98757    0.52533    0.097456
  0.8822     0.51221    0.40204    0.21169   -0.013109  -0.71616
  0.55387    1.1452    -0.88044   -0.50216   -0.22814    0.023885
  0.1072     0.083739   0.55015    0.58479    0.75816    0.45706
 -0.28001    0.25225    0.68965   -0.60972    0.19578    0.044209
 -0.31136   -0.68826   -0.22721    0.46185   -0.77162    0.10208
  0.55636    0.067417  -0.57207    0.23735    0.4717     0.82765
 -0.29263   -1.3422    -0.099277   0.28139    0.41604    0.10583
  0.62203    0.89496   -0.23446    0.51349    0.99379    1.1846
 -0.16364    0.20653    0.73854    0.24059   -0.96473    0.13481
 -0.0072484  0.33016   -0.12365    0.27191   -0.40951    0.021909
 -0.6069     0.40755    0.19566   -0.41802    0.18636   -0.032652
 

[('dog', 0.8798074722290039),
 ('rabbit', 0.7424427270889282),
 ('cats', 0.732300341129303),
 ('monkey', 0.7288709878921509),
 ('pet', 0.719014048576355),
 ('dogs', 0.7163872718811035),
 ('mouse', 0.6915250420570374),
 ('puppy', 0.6800068020820618),
 ('rat', 0.6641027331352234),
 ('spider', 0.6501135230064392)]

In [2]:
import pandas as pd

glove_data=pd.DataFrame()
